---
title: "robust idea"
author: "Haozhe Wang"
date: '2022-12-05'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## prepare section



```{r }
require(stats4)
set.seed(7)
sd1 <-0.1
sd2 <-0.1
# x_1 follow the normal distribution with 0 mean 0.1 sd
x_1 <- rnorm(1200,0,sd1)

# x_2 follow the normal distribution with 0 mean 0.1 sd
x_2 <- rnorm(1200,0,sd1)

# x_3 follow the normal distribution with 0 mean 0.1 sd
x_3 <- rnorm(1200,0,sd1)

# set the epsilon follow the normal distribution with 0 mean 0.1 sd
epsilon_1 <- rnorm(1200,0,sd2)

h <- function (x) 1/x

# set Y_1 and Y_2 
Y_1 <- 2-0.5*x_1+3*x_2+4*x_3+epsilon_1
Y_2 <- h(Y_1)

# check Y_1 >0 or not
#length(which(Y_1<=0 ))

# set a data frame
dataframe <- data.frame(x_1,x_2,x_3,Y_1,Y_2)

```

## plot the relationship between Y and X



```{r pressure, echo=FALSE}
# require library 
require(ggpubr)
library(ggplot2)
library(tibble)

fun <- function(x){
  (x-min(x)) / (max(x)-min(x))
  }

dataframe_norm <- dataframe
dataframe_norm[,1] <- fun(dataframe[,1])
dataframe_norm[,2] <- fun(dataframe[,2])
dataframe_norm[,3] <- fun(dataframe[,3])
dataframe_norm[,4] <- fun(dataframe[,4])
dataframe_norm[,5] <- fun(dataframe[,5])

p1 <- ggplot(data = dataframe_norm,aes(x=x_1,y=Y_1))+geom_point()
p2 <- ggplot(data = dataframe_norm,aes(x=x_2,y=Y_1))+geom_point()
p3 <- ggplot(data = dataframe_norm,aes(x=x_3,y=Y_1))+geom_point()
p4 <- ggplot(data = dataframe_norm,aes(x=x_1,y=Y_2))+geom_point()
p5 <- ggplot(data = dataframe_norm,aes(x=x_2,y=Y_2))+geom_point()
p6 <- ggplot(data = dataframe_norm,aes(x=x_3,y=Y_2))+geom_point()

ggarrange(p1,p2,p3,p4,p5,p6,ncol = 3,nrow =2,widths = c(1,2),heights = c(1,1,2))


```

## model fitting

### model 1
```{r}
# model 1 fit Y_1 and Y_2 independently.

# fit Y_1
model_1_Y_1 <- lm(Y_1~x_1+x_2+x_3,dataframe[1:1000,])
summary(model_1_Y_1)

# fit Y_2
model_1_Y_2_lm <- lm(Y_2~x_1+x_2+x_3,dataframe[1:1000,])
summary(model_1_Y_2_lm)

# use xgboost to fit Y_2
library(xgboost)
model_1_Y_2_xgboost <- xgboost(
  data = as.matrix(dataframe[1:1000,1:3]),
  label =  as.matrix(dataframe[1:1000,5]),
   max_depth =4, eta = 1, nthread = 2, nrounds = 2
)
summary(model_1_Y_2_xgboost)

vec_training<- c(1:1000)
vec_test <- c(1001:1200)
# predict vector
predict_1_Y_1_training <- predict.lm(model_1_Y_1,dataframe[vec_training,1:3])

predict_1_Y_2_training <- predict(model_1_Y_2_xgboost ,as.matrix(dataframe[vec_training,1:3]))

predict_1_Y_1_test <- predict.lm(model_1_Y_1,dataframe[vec_test,1:3])

predict_1_Y_2_test <- predict(model_1_Y_2_xgboost ,as.matrix(dataframe[vec_test,1:3]))
```
### model 2
```{r}
predict_2_Y_1_training <-  predict_1_Y_1_training
predict_2_Y_2_training <-  h(predict_2_Y_1_training)
predict_2_Y_1_test <-  predict_1_Y_1_test
predict_2_Y_2_test <-  h(predict_2_Y_1_test)
```


### model 3
```{r}

#define function to minimize residual sum of squares
min_residuals <- function(data, par_,lambda) {
   s1 <- lambda* 
    with(data, sum((par_[1] + par_[2] * x_1+ par_[3] * x_2+ par_[4] * x_3 - Y_1)^2))
   s2 <- (1-lambda)* 
    with(data, sum((h(par_[1] + par_[2] * x_1+ par_[3] * x_2+ par_[4] * x_3) - Y_2)^2))
   s1+s2
}

# calculate s1 without lambda

s1_fn <- function(data, par_) {
  
    with(data, sum((par_[1] + par_[2] * x_1+ par_[3] * x_2+ par_[4] * x_3 - Y_1)^2))
}

# calculate s2 without (1-lambda)
s2_fn <- function(data, par_) {
  
    with(data, sum((h(par_[1] + par_[2] * x_1+ par_[3] * x_2+ par_[4] * x_3) - Y_2)^2))
}


res_value <- c()
lambda_value <- c()
lambda_value[1] <-1
sample_num <- 200




for (i in 1:sample_num){
  # minimize the parameter
  res <- optim(c(1,-1,1,1), min_residuals,data=dataframe[1:1000,],lambda=lambda_value[i], 
               lower=c(-Inf, -Inf, -Inf, -Inf), upper=c(Inf, Inf, Inf, Inf),
      method="L-BFGS-B")
  
  res_value[i] <- res$value
  
  # calculate the new lambda
  s1 <-  s1_fn (data=dataframe[1:1000,],res$par)
  s2 <-  s2_fn (data=dataframe[1:1000,],res$par)
  lambda_value[i+1] <- s2/(s1+s2)
  
  # if lambda does not change to much stop
  if (abs(lambda_value[i+1]-lambda_value[i])<1e-7){
    break()
  }
}

if (abs(lambda_value[length(lambda_value)]-lambda_value[length(lambda_value)-1])>1e-7){
    cat("not converge")
  }

parmeter_3 <-c( res$par)
lambda_3 <-  lambda_value[length(lambda_value)]


predict_3_Y_1_training <-  cbind(rep(1,length(vec_training)),as.matrix(dataframe[vec_training,1:3]))%*%parmeter_3
predict_3_Y_2_training <-  h(predict_3_Y_1_training)

predict_3_Y_1_test <-  cbind(rep(1,length(vec_test)),as.matrix(dataframe[vec_test,1:3]))%*%parmeter_3
predict_3_Y_2_test <-  h(predict_3_Y_1_test)


```

## Evaluation
```{r}
# mean square error
MSE_fn <- function(predict,true){
 sum((predict - true)^2)/(length(predict)-1) 
} 

# R square
R2_fn <- function(predict,true){
  cor(predict,true)^2
} 


Y_1_true_training <- c(dataframe[vec_training,4])
Y_2_true_training <- c(dataframe[vec_training,5])
MSE_1_Y_1_training <- MSE_fn(predict_1_Y_1_training,Y_1_true_training) 
MSE_2_Y_1_training <- MSE_fn(predict_2_Y_1_training,Y_1_true_training) 
MSE_3_Y_1_training <- MSE_fn(predict_3_Y_1_training,Y_1_true_training) 
MSE_1_Y_2_training <- MSE_fn(predict_1_Y_2_training,Y_2_true_training) 
MSE_2_Y_2_training <- MSE_fn(predict_2_Y_2_training,Y_2_true_training) 
MSE_3_Y_2_training <- MSE_fn(predict_3_Y_2_training,Y_2_true_training)


R2_1_Y_1_training <- R2_fn(predict_1_Y_1_training,Y_1_true_training) 
R2_2_Y_1_training <- R2_fn(predict_2_Y_1_training,Y_1_true_training) 
R2_3_Y_1_training <- R2_fn(predict_3_Y_1_training,Y_1_true_training) 
R2_1_Y_2_training <- R2_fn(predict_1_Y_2_training,Y_2_true_training) 
R2_2_Y_2_training <- R2_fn(predict_2_Y_2_training,Y_2_true_training) 
R2_3_Y_2_training <- R2_fn(predict_3_Y_2_training,Y_2_true_training)


matrix_mse_training <- matrix(c(MSE_1_Y_1_training,MSE_2_Y_1_training,MSE_3_Y_1_training,
                                MSE_1_Y_2_training,MSE_2_Y_2_training,MSE_3_Y_2_training),nrow=3,ncol=2)
matrix_mse_training

matrix_R2_training <- matrix(c(R2_1_Y_1_training,R2_2_Y_1_training,R2_3_Y_1_training,
                               R2_1_Y_2_training,R2_2_Y_2_training,R2_3_Y_2_training),nrow=3,ncol=2)
matrix_R2_training


Y_1_true_test <- c(dataframe[vec_test,4])
Y_2_true_test <- c(dataframe[vec_test,5])
MSE_1_Y_1_test <- MSE_fn(predict_1_Y_1_test,Y_1_true_test) 
MSE_2_Y_1_test <- MSE_fn(predict_2_Y_1_test,Y_1_true_test) 
MSE_3_Y_1_test <- MSE_fn(predict_3_Y_1_test,Y_1_true_test) 
MSE_1_Y_2_test <- MSE_fn(predict_1_Y_2_test,Y_2_true_test) 
MSE_2_Y_2_test <- MSE_fn(predict_2_Y_2_test,Y_2_true_test) 
MSE_3_Y_2_test <- MSE_fn(predict_3_Y_2_test,Y_2_true_test)


R2_1_Y_1_test <- R2_fn(predict_1_Y_1_test,Y_1_true_test) 
R2_2_Y_1_test <- R2_fn(predict_2_Y_1_test,Y_1_true_test) 
R2_3_Y_1_test <- R2_fn(predict_3_Y_1_test,Y_1_true_test) 
R2_1_Y_2_test <- R2_fn(predict_1_Y_2_test,Y_2_true_test) 
R2_2_Y_2_test <- R2_fn(predict_2_Y_2_test,Y_2_true_test) 
R2_3_Y_2_test <- R2_fn(predict_3_Y_2_test,Y_2_true_test)


matrix_mse_test <- matrix(c(MSE_1_Y_1_test,MSE_2_Y_1_test,MSE_3_Y_1_test,MSE_1_Y_2_test,
                            MSE_2_Y_2_test,MSE_3_Y_2_test),nrow=3,ncol=2)
matrix_mse_test

matrix_R2_test <- matrix(c(R2_1_Y_1_test,R2_2_Y_1_test,R2_3_Y_1_test,R2_1_Y_2_test,
                           R2_2_Y_2_test,R2_3_Y_2_test),nrow=3,ncol=2)
matrix_R2_test



predict_data_training_Y_1 <- data.frame(predict_1_Y_1_training,predict_2_Y_1_training,predict_3_Y_1_training,Y_1_true_training)

predict_data_training_Y_2 <- data.frame(predict_1_Y_2_training,predict_2_Y_2_training,predict_3_Y_2_training,Y_2_true_training)

predict_data_test_Y_1 <- data.frame(predict_1_Y_1_test,predict_2_Y_1_test,predict_3_Y_1_test,Y_1_true_test)

predict_data_test_Y_2 <- data.frame(predict_1_Y_2_test,predict_2_Y_2_test,predict_3_Y_2_test,Y_2_true_test)
```


## matrix change to latex code
```{r}
require(xtable)
xtable(matrix_mse_test, type = "latex")
xtable(matrix_R2_test, type = "latex")
```




